networks:
  monitor-net:
    driver: bridge

volumes:
    postgres_data: {}


services:



######################################################################################
#####################           INDEX NODE CONTAINER 0         #######################
######################################################################################


  index-node-0:
    image: ${GRAPH_NODE_VERSION:-graphprotocol/graph-node:v0.35.1}
    container_name: index-node-0
    depends_on:
      - postgres
    volumes:
      - ./graph-node-configs:/root/graph-node-configs/
      - ./postgres-socket:/var/run/postgresql
    environment:
      GRAPH_NODE_CONFIG: /root/graph-node-configs/config.toml
      ipfs: '${IPFS_ENDPOINT:-https://ipfs.network.thegraph.com/ipfs/}'
      node_role: index-node
      node_id: index_node_0
      BLOCK_INGESTOR: index_node_0
      GRAPH_LOG: ${GRAPHNODE_LOGLEVEL:-DEBUG}
      GRAPH_ETH_CALL_GAS: 50000000
      GRAPH_GETH_ETH_CALL_ERRORS: "out of gas"
      GRAPH_MAX_GAS_PER_HANDLER: 1000000000000000
      GRAPH_KILL_IF_UNRESPONSIVE: "true"
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: ${FULLTEXT_SEARCH:-true}
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: ${GRAPH_ALLOW_NON_DETERMINISTIC_IPFS:-true}
      EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: synced
      ETHEREUM_POLLING_INTERVAL: ${RPC_POLLING_RATE:-500}
      GRAPH_ETH_CALL_NO_GAS: "421613,42161"
    restart: unless-stopped
    expose:
      - 8001
      - 8000
      - 8030
      - 8040
    networks:
      - monitor-net


######################################################################################
#####################           QUERY NODE CONTAINER 0         #######################
######################################################################################


  query-node-0:
    image: ${GRAPH_NODE_VERSION:-graphprotocol/graph-node:v0.35.1}
    container_name: query-node-0
    depends_on:
      - postgres
    volumes:
      - ./graph-node-configs:/root/graph-node-configs/
      - ./postgres-socket:/var/run/postgresql
    environment:
      GRAPH_NODE_CONFIG: /root/graph-node-configs/config.toml
      ipfs: '${IPFS_ENDPOINT:-https://ipfs.network.thegraph.com/ipfs/}'
      node_role: query-node
      node_id: query_node_0
      GRAPH_LOG: INFO
      GRAPH_ETH_CALL_GAS: 50000000
      GRAPH_GETH_ETH_CALL_ERRORS: "out of gas"
      GRAPH_MAX_GAS_PER_HANDLER: 1000000000000000
      EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: synced
      GRAPH_KILL_IF_UNRESPONSIVE: "true"
      GRAPH_LOG_QUERY_TIMING: ${GRAPH_LOG_QUERY_TIMING:-gql}
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: ${FULLTEXT_SEARCH:-true}
    restart: unless-stopped
    logging:
        driver: "journald"
    expose:
      - 8001
      - 8000
      - 8020
      - 8030
      - 8040
    networks:
      - monitor-net


######################################################################################
#####################            POSTGRES CONTAINER            #######################
######################################################################################



  postgres:
    image: ${POSTGRES_VERSION:-postgres:16.4}
    container_name: postgres
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${GRAPH_NODE_DB_USER:-your_db_user}
      POSTGRES_PASSWORD: ${GRAPH_NODE_DB_PASS:-your_db_password}
      POSTGRES_DB: ${GRAPH_NODE_DB_NAME:-your_graphnode_db_name}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitor-net
    expose:
      - 5432
