version: "2.1"

x-logging: &default-logging
  options:
    max-file: "1"
    compress: "false"
  driver: local

networks:
  monitor-net:
    driver: bridge

services:
  ######################################################################################
  #####################           SUBGRAPH RADIO CONTAINER            ##################
  ######################################################################################

  subgraph-radio:
    image: ghcr.io/graphops/subgraph-radio:0.1
    container_name: subgraph-radio
    expose:
      - 3010
      - 3012
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GRAPHCAST_NETWORK: ${GRAPHCAST_NETWORK:-mainnet}
      REGISTRY_SUBGRAPH: ${REGISTRY_SUBGRAPH:-https://api.thegraph.com/subgraphs/name/hopeyen/graphcast-registry-mainnet}
      NETWORK_SUBGRAPH: ${NETWORK_SUBGRAPH:-https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet}
      MNEMONIC: ${OPERATOR_SEED_PHRASE_MAINNET}
      GRAPH_NODE_STATUS_ENDPOINT: ${GRAPH_NODE_STATUS_ENDPOINT:-http://index-node-0:8030/graphql}
      RUST_LOG: ${RUST_LOG:-warn,hyper=warn,graphcast_sdk=info,subgraph_radio=info}
      INDEXER_ADDRESS: ${STAKING_WALLET_ADDRESS_MAINNET}
      METRICS_HOST: ${METRICS_HOST:-0.0.0.0}
      METRICS_PORT: ${METRICS_PORT:-3010}
      SERVER_PORT: ${SERVER_PORT:-3012}
      ID_VALIDATION: ${ID_VALIDATION:-indexer}
      COVERAGE: ${COVERAGE:-comprehensive}
      PERSISTENCE_FILE_PATH: ${PERSISTENCE_FILE_PATH:-./state.json}
    networks:
      - monitor-net
    logging: *default-logging

  ######################################################################################
  #####################           POIFIER CONTAINER              #######################
  ######################################################################################

  poifier:
    image: grassets/poifier-client:v2.0.3
    container_name: poifier
    command:
      - "--poifier-server=https://poifier.io"
      - "--graph-node-status-endpoint=http://index-node-0:8030/graphql"
      - "--mnemonic=${OPERATOR_SEED_PHRASE}"
      - "--indexer-address=${STAKING_WALLET_ADDRESS}"
      - "--indexer-agent-epoch-subgraph-endpoint=${INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT:-https://api.thegraph.com/subgraphs/name/graphprotocol/mainnet-epoch-block-oracle}"
    tty: true
    networks:
      - monitor-net
    restart: unless-stopped

  ######################################################################################
  #####################            INDEXER AGENT GUI             #######################
  ######################################################################################

  indexer-agent-gui:
    image: ${INDEXER_AGENT_GUI:-ghcr.io/stakemachine/indexer-agent-ui:v0.1.15}
    container_name: indexer-agent-gui
    expose:
      - 3000
    environment:
      - UI_LOGIN=${ADMIN_USER:-test}
      - UI_PASS=${ADMIN_PASSWORD:-pass}
      - AGENT_ENDPOINT=${INDEXER_AGENT_ENDPOINT:-http://indexer-agent:8000}
      - SUBGRAPH_ENDPOINT=${INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT:-https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${AGENT_GUI_HOST}/
    restart: unless-stopped
    networks:
      - monitor-net
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.indexer-agent-gui.loadbalancer.server.port=3000"
      - "traefik.http.routers.indexer-agent-gui.entrypoints=websecure"
      - "traefik.http.routers.indexer-agent-gui.tls.certresolver=myresolver"
      - "traefik.http.routers.indexer-agent-gui.rule=Host(`$AGENT_GUI_HOST`)"

  ######################################################################################
  #####################         TRAEFIK PROXY CONTAINER          #######################
  ######################################################################################

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    expose:
      - "8082"
    ports:
      - "443:443"
      - "80:80"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic_config.yml"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # TESTING
      - "--certificatesresolvers.myresolver.acme.email=$EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/config/dynamic_config.yml:/dynamic_config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - monitor-net
    labels:
      - "traefik.enable=true"
