{
 "title": "Custom Indexing Panels",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Individual subgraph sync rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(deriv(deployment_blocks_behind[10m]) * -60)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "All subgraphs sync rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(deployment_blocks_behind[10m]) * -60)"
    }
   ]
  },
  {
   "title": "Blocks behind over time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "deployment_blocks_behind", "legendFormat": "{{deployment}}" }
   ]
  },
  {
   "title": "Eth RPC Request Duration per Subgraph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(deployment_eth_rpc_request_duration[15m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Eth RPC Errors per minute (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(eth_rpc_errors[1m]))"
    }
   ]
  },
  {
   "title": "Blocks behind over time (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(deployment_blocks_behind)" }
   ]
  },
  {
   "title": "Blocks Processed per Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(deployment_block_processing_duration_sum[1m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Blocks Processed per Minute (all subgraphs)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_sum[1m]))"
    }
   ]
  }
 ]
}