{
 "title": "Postgres Activity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "store_connection_checkout_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "store_connection_checkout_count",
     "legendFormat": "{{job}} - {{shard}}"
    }
   ]
  },
  {
   "title": "store_connection_error_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "store_connection_error_count", "legendFormat": "{{job}} - {{shard}}" }
   ]
  },
  {
   "title": "store_connection_wait_time_ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "store_connection_wait_time_ms", "legendFormat": "{{job}} - {{shard}}" }
   ]
  },
  {
   "title": "Transactions until wraparound vacuum",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nSELECT\n  relname as table,\n  least((SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_freeze_max_age') - age(relfrozenxid), \n        (SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_multixact_freeze_max_age') - mxid_age(relminmxid))\n        tx_before_wraparound_vacuum,\n  pg_stat_get_last_autovacuum_time(c.oid) AS last_autovacuum,\n  age(relfrozenxid) AS xid_age,\n  mxid_age(relminmxid) AS mxid_age\nFROM\n  pg_class c\nWHERE\n  c.relname in ('ethereum_blocks', 'eth_call_cache','subgraph_deployment')\n  and c.relfrozenxid != 0\n"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT left(ds.shard, 20) shard, count(ds.id) \"all\", count(a.id) assigned from deployment_schemas ds left outer join subgraphs.subgraph_deployment_assignment a on a.id = ds.id group by 1 order by 1"
    }
   ]
  },
  {
   "title": "Tables requiring wraparound vacuum",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 27 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nSELECT\n  left(n.nspname || '.' || c.relname, 25) as table,\n  least((SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_freeze_max_age') - age(relfrozenxid), \n        (SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_multixact_freeze_max_age') - mxid_age(relminmxid))\n        tx_before_wraparound_vacuum,\n  greatest(pg_stat_get_last_autovacuum_time(c.oid), pg_stat_get_last_vacuum_time(c.oid)) AS last_vacuum,\n  c.relpages::numeric*8192 as table_size,\n  c.reltuples as table_rows\n  -- age(relfrozenxid) AS xid_age,\n  -- mxid_age(relminmxid) AS mxid_age\nFROM\n  pg_class c, pg_namespace n\nWHERE\n  n.oid = c.relnamespace\n  -- c.relname in ('event_meta_data', 'ethereum_blocks','ens_names','eth_call_cache')\n  and c.relkind in ('r','m')\n  and c.oid > 16384\n  and (SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_freeze_max_age') < age(relfrozenxid)\n  and c.relfrozenxid != 0\n"
    }
   ]
  },
  {
   "title": "Deployment usage",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect count(*) unused,\n       (select count(*) from unused_deployments where removed_at is null) recorded,\n       (select count(distinct deployment) from subgraphs.subgraph_version where created_at >= extract(epoch from now() - '24h'::interval)) \"new (24h)\",\n       (select count(*) from subgraphs.subgraph_deployment_assignment where node_id like 'index_node_%') as \"assigned\",\n       (select count(*) from deployment_schemas) total\n  from deployment_schemas ds\n where not exists (select 1 from subgraphs.subgraph_deployment_assignment sda where ds.id=sda.id)\n   and not exists (select 1 from subgraphs.subgraph_version v, subgraphs.subgraph s where ds.subgraph = v.deployment and v.id in (s.current_version, s.pending_version))"
    }
   ]
  },
  {
   "title": "Total WAL size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(size) as size from pg_ls_waldir();"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect regexp_replace(regexp_replace(regexp_replace(coalesce(nullif(application_name,''), 'unknown'),\n                      'query_node_[0-9a-f]+_', 'q-'),\n                      'query_node_high_traffic_[0-9a-f]+_', 'h-'),\n                      'index_node_(customer_)?', 'i-') as client,\n       pid,\n       extract(epoch from age(now(), query_start)) as age,\n       extract(epoch from age(now(), xact_start)) as txn_age,\n       format('%s'||chr(10)||'%s'||chr(10)||'block: %s', variadic (coalesce((select regexp_matches(query, '^/\\*.*application=''([^'']+)'',route=''([^'']+)''.*action=''([^'']+)''.*\\*/.*$')), array['ø', 'ø', 'ø']))) as qid,\n       regexp_replace(query, '^/\\* controller=''filter''.*? \\*/', '') as query\n  from pg_stat_activity\n where query not like '%grafana ignore%'\n   and state='active'\n   and coalesce(usename, 'none') != 'cloudsqlreplica'\n   and query not like '[[autovacuum]]: %'\norder by query_start desc"
    }
   ]
  },
  {
   "title": "Bloat Report",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect u.relname,\n       u.n_live_tup, \n       u.n_dead_tup, \n       u.n_dead_tup::numeric/nullif(u.n_live_tup,0)::numeric as bloat_factor, \n       c.relpages,\n       age(now(), greatest(u.last_autovacuum, u.last_vacuum))::text last_vacuum\n  from pg_stat_user_tables u, pg_class c\n where u.schemaname in ('subgraphs','public')\n   and u.relid = c.oid\n   and u.n_dead_tup > 100"
    }
   ]
  },
  {
   "title": "Active grafts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\r\nselect ac.src, \r\n       src.subgraph as src_subgraph,\r\n       src.shard as src_shard,\r\n       ac.dst,\r\n       dst.subgraph as dst_subgraph,\r\n       dst.shard as dst_shard,\r\n       ac.queued_at,\r\n       ac.cancelled_at \r\n  from active_copies ac,\r\n       deployment_schemas src,\r\n       deployment_schemas dst\r\n where ac.src = src.id\r\n   and ac.dst = dst.id;\r\n"
    }
   ]
  },
  {
   "title": "Active locks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nSELECT  a.application_name,\n        coalesce(extract(epoch from age(now(), a.xact_start)), 0) as age,\n        l.relation::regclass,\n        l.mode,\n        l.GRANTED::varchar,\n        l.locktype \"Target\",\n        l.pid\nFROM pg_stat_activity a\nJOIN pg_locks l ON l.pid = a.pid\nwhere pg_backend_pid() != a.pid\norder by granted asc, age desc;"
    }
   ]
  },
  {
   "title": "Idle transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect client_addr,\n       application_name,\n       usename,\n       state,\n       extract(epoch from age(now(), xact_start)) as age\n  from pg_stat_activity\n where query not like '%grafana ignore%'\n   and state like '%idle in transaction%'\norder by query_start desc"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "{service_name=\"/postgres\"} | logfmt"
    }
   ]
  }
 ]
}