{
 "title": "Query Performance Metrics v2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average Queries per Second for the interval",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(indexer_query_handler_seconds_count[1m]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(indexer_query_handler_failed_total[1m]))",
     "legendFormat": "FAIL"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(indexer_query_handler_failed_total)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_query_handler_seconds_count)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_query_handler_failed_total[10s]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_query_handler_seconds_count[10s]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total queries by subgraph per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (deployment) (rate(indexer_query_handler_seconds_count[10s]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Total queries per deployment since last restart",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sort_desc(sum by (deployment) (indexer_query_handler_seconds_count))",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Indexer / Total errors count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "indexer_error", "legendFormat": "{{code}}  /  {{job}}" }
   ]
  },
  {
   "title": "Cost Model Queries over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(indexer_cost_model_batch_seconds_count)",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(indexer_cost_model_batch_failed_total)",
     "legendFormat": "batch queries_failed"
    }
   ]
  },
  {
   "title": "Indexer errors (over 5 minutes, by code)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(indexer_error[30s])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total Cost Model Batch Queries by Servicenode per second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(indexer_cost_model_batch_seconds_count[10s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cost Model Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(indexer_cost_model_batch_seconds_count[1m]))",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(rate(indexer_cost_model_batch_failed_total[1m]))",
     "legendFormat": "batch queries_failed"
    }
   ]
  }
 ]
}